services:
  blog:
    image: jekyll/jekyll:latest
    command: jekyll serve --force_polling --drafts --livereload --trace
    platform: linux/amd64
    ports:
      - "4000:4000"
    volumes:
      - ".:/srv/jekyll"
